### ISSUE TITLE
Minikube binary installation e2e test case implementation

### ISSUE THREAD

**Issue by odockal** [podman-desktop/extension-minikube#138]
Cover the scenario for minikube binary installation using playwright e2e test support.

Similarly as with kind, installation of the binary might be also system wide, where we need additional test environment preparation to avoid system native dialog for running the command in elevated mode.

So the behavior differs on linux, windows and mac.

**Comment by axel7083** [comment]
The https://github.com/containers/podman-desktop-extension-minikube/issues/149 ticket will be resolved with https://github.com/containers/podman-desktop-extension-minikube/pull/201, so the e2e might change for the `binary installation`.

I would recommend to wait for the following to be merged
- https://github.com/containers/podman-desktop-extension-minikube/issues/149
