### ISSUE TITLE
Replace `process.platform` by `extensionApi.env.is<platform>`

### ISSUE THREAD

**Issue by axel7083** [podman-desktop/extension-minikube#176]
While working on next release, there is a lot of code using either `process.platform === 'linux'` and `extensionApi.env.isLinux` in the same file.

This makes it pretty hard to write tests, and we should stop using `process.platform`.

**Comment by afbjorklund** [comment]
This is because the copied code is not updated with the rest of Podman Desktop, due to being forced into a separate project.
