### ISSUE TITLE
Test Minikube 0.4.0 release

### ISSUE THREAD

**Issue by odockal** [podman-desktop/extension-minikube#214]
Since we have minikube 0.4.0 tag available, it would be great to smoke test the release on linux, mac and windows.

**Comment by odockal** [comment]
@amisskii Please take a look, thanks!

**Comment by odockal** [comment]
Found issues: https://github.com/podman-desktop/extension-minikube/issues/215

**Comment by amisskii** [comment]
QE approves the release of the Podman Desktop Minikube Extension 0.4.0.

Issues discovered during testing:

https://github.com/podman-desktop/extension-minikube/issues/152
https://github.com/podman-desktop/extension-minikube/issues/215
https://github.com/podman-desktop/extension-minikube/issues/216
